import styles from '@/assets/css/SingleBlog.module.css';
import Image from 'next/image';

import hero from "@/assets/images/covid-hero.jpg"

export default function Blog() {

    return (
        <main>
            <section className={styles.hero}>
                <Image src={hero} alt='' />
                <div className={styles.overlay}></div>
                <h1>Navigating COVID-19: Tips, Updates, and Resources for Your Health and Safety</h1>
            </section>
            <div className={styles.body}>
                <p><span className={styles.firstLetter}>L</span>orem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis, adipisci officia harum nobis eligendi assumenda esse est doloribus ut voluptas doloremque veniam necessitatibus quaerat corporis nemo corrupti aliquid quibusdam nisi animi et neque optio. Error laudantium suscipit nihil sequi repellendus quidem blanditiis quisquam incidunt dicta odit facere deleniti, pariatur voluptatum itaque non necessitatibus quibusdam nostrum. Saepe sed facere reiciendis excepturi molestiae odit alias assumenda nostrum. Temporibus neque nemo, hic eveniet commodi similique suscipit, delectus dolor quas magnam placeat quod, omnis dolores deserunt. Pariatur quod voluptate aperiam delectus dolores. Corrupti, optio accusantium? Cupiditate totam magni quidem reprehenderit eaque tempore labore quo!</p>
                <div className={styles.stage}>
                    <div className={styles.item}>
                        <h2>Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis optio quam excepturi autem ipsam dolore dolorum inventore deleniti mollitia ipsum. Dignissimos, illo ea iure, veniam mollitia eius officiis dolorem soluta officia possimus numquam quos, architecto in? Aliquam vitae, pariatur ut ducimus veniam quas, libero corporis itaque possimus modi, vel assumenda.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis optio quam excepturi autem ipsam dolore dolorum inventore deleniti mollitia ipsum. Dignissimos, illo ea iure, veniam mollitia eius officiis dolorem soluta officia possimus numquam quos, architecto in? Aliquam vitae, pariatur ut ducimus veniam quas, libero corporis itaque possimus modi, vel assumenda.</p>
                    </div>
                    <div className={styles.item}>
                        <h2>Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis optio quam excepturi autem ipsam dolore dolorum inventore deleniti mollitia ipsum. Dignissimos, illo ea iure, veniam mollitia eius officiis dolorem soluta officia possimus numquam quos, architecto in? Aliquam vitae, pariatur ut ducimus veniam quas, libero corporis itaque possimus modi, vel assumenda.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis optio quam excepturi autem ipsam dolore dolorum inventore deleniti mollitia ipsum. Dignissimos, illo ea iure, veniam mollitia eius officiis dolorem soluta officia possimus numquam quos, architecto in? Aliquam vitae, pariatur ut ducimus veniam quas, libero corporis itaque possimus modi, vel assumenda.</p>
                    </div>
                </div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus dolor provident voluptatem beatae impedit sint possimus tempora libero neque tenetur deserunt, magnam nostrum deleniti repellat corrupti est debitis in saepe? Culpa aliquam nulla, eos eius amet temporibus architecto dolorem similique fugiat non sit quae tenetur tempora, incidunt reiciendis beatae illum quia numquam. Magnam aperiam porro aut ullam cupiditate repellendus impedit, voluptatibus fugiat expedita incidunt vero quam provident? Id minima quidem tenetur porro repudiandae consequatur placeat autem et, distinctio dolorum non iure delectus soluta repellendus eos. Cupiditate, provident. Officia, ullam. Atque saepe facere unde in nesciunt esse assumenda cupiditate id enim!</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus dolor provident voluptatem beatae impedit sint possimus tempora libero neque tenetur deserunt, magnam nostrum deleniti repellat corrupti est debitis in saepe? Culpa aliquam nulla, eos eius amet temporibus architecto dolorem similique fugiat non sit quae tenetur tempora, incidunt reiciendis beatae illum quia numquam. Magnam aperiam porro aut ullam cupiditate repellendus impedit, voluptatibus fugiat expedita incidunt vero quam provident? Id minima quidem tenetur porro repudiandae consequatur placeat autem et, distinctio dolorum non iure delectus soluta repellendus eos. Cupiditate, provident. Officia, ullam. Atque saepe facere unde in nesciunt esse assumenda cupiditate id enim!</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus dolor provident voluptatem beatae impedit sint possimus tempora libero neque tenetur deserunt, magnam nostrum deleniti repellat corrupti est debitis in saepe? Culpa aliquam nulla, eos eius amet temporibus architecto dolorem similique fugiat non sit quae tenetur tempora, incidunt reiciendis beatae illum quia numquam. Magnam aperiam porro aut ullam cupiditate repellendus impedit, voluptatibus fugiat expedita incidunt vero quam provident? Id minima quidem tenetur porro repudiandae consequatur placeat autem et, distinctio dolorum non iure delectus soluta repellendus eos. Cupiditate, provident. Officia, ullam. Atque saepe facere unde in nesciunt esse assumenda cupiditate id enim!</p>
                <h2>Lorem Ipsum</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus dolor provident voluptatem beatae impedit sint possimus tempora libero neque tenetur deserunt, magnam nostrum deleniti repellat corrupti est debitis in saepe? Culpa aliquam nulla, eos eius amet temporibus architecto dolorem similique fugiat non sit quae tenetur tempora, incidunt reiciendis beatae illum quia numquam. Magnam aperiam porro aut ullam cupiditate repellendus impedit, voluptatibus fugiat expedita incidunt vero quam provident? Id minima quidem tenetur porro repudiandae consequatur placeat autem et, distinctio dolorum non iure delectus soluta repellendus eos. Cupiditate, provident. Officia, ullam. Atque saepe facere unde in nesciunt esse assumenda cupiditate id enim!</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus dolor provident voluptatem beatae impedit sint possimus tempora libero neque tenetur deserunt, magnam nostrum deleniti repellat corrupti est debitis in saepe? Culpa aliquam nulla, eos eius amet temporibus architecto dolorem similique fugiat non sit quae tenetur tempora, incidunt reiciendis beatae illum quia numquam. Magnam aperiam porro aut ullam cupiditate repellendus impedit, voluptatibus fugiat expedita incidunt vero quam provident? Id minima quidem tenetur porro repudiandae consequatur placeat autem et, distinctio dolorum non iure delectus soluta repellendus eos. Cupiditate, provident. Officia, ullam. Atque saepe facere unde in nesciunt esse assumenda cupiditate id enim!</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus dolor provident voluptatem beatae impedit sint possimus tempora libero neque tenetur deserunt, magnam nostrum deleniti repellat corrupti est debitis in saepe? Culpa aliquam nulla, eos eius amet temporibus architecto dolorem similique fugiat non sit quae tenetur tempora, incidunt reiciendis beatae illum quia numquam. Magnam aperiam porro aut ullam cupiditate repellendus impedit, voluptatibus fugiat expedita incidunt vero quam provident? Id minima quidem tenetur porro repudiandae consequatur placeat autem et, distinctio dolorum non iure delectus soluta repellendus eos. Cupiditate, provident. Officia, ullam. Atque saepe facere unde in nesciunt esse assumenda cupiditate id enim!</p>
                <div className={styles.stage}>
                    <div className={styles.item}>
                        <h2>Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis optio quam excepturi autem ipsam dolore dolorum inventore deleniti mollitia ipsum. Dignissimos, illo ea iure, veniam mollitia eius officiis dolorem soluta officia possimus numquam quos, architecto in? Aliquam vitae, pariatur ut ducimus veniam quas, libero corporis itaque possimus modi, vel assumenda.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis optio quam excepturi autem ipsam dolore dolorum inventore deleniti mollitia ipsum. Dignissimos, illo ea iure, veniam mollitia eius officiis dolorem soluta officia possimus numquam quos, architecto in? Aliquam vitae, pariatur ut ducimus veniam quas, libero corporis itaque possimus modi, vel assumenda.</p>
                    </div>
                    <div className={styles.item}>
                        <h2>Lorem Ipsum</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis optio quam excepturi autem ipsam dolore dolorum inventore deleniti mollitia ipsum. Dignissimos, illo ea iure, veniam mollitia eius officiis dolorem soluta officia possimus numquam quos, architecto in? Aliquam vitae, pariatur ut ducimus veniam quas, libero corporis itaque possimus modi, vel assumenda.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis optio quam excepturi autem ipsam dolore dolorum inventore deleniti mollitia ipsum. Dignissimos, illo ea iure, veniam mollitia eius officiis dolorem soluta officia possimus numquam quos, architecto in? Aliquam vitae, pariatur ut ducimus veniam quas, libero corporis itaque possimus modi, vel assumenda.</p>
                    </div>
                </div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus dolor provident voluptatem beatae impedit sint possimus tempora libero neque tenetur deserunt, magnam nostrum deleniti repellat corrupti est debitis in saepe? Culpa aliquam nulla, eos eius amet temporibus architecto dolorem similique fugiat non sit quae tenetur tempora, incidunt reiciendis beatae illum quia numquam. Magnam aperiam porro aut ullam cupiditate repellendus impedit, voluptatibus fugiat expedita incidunt vero quam provident? Id minima quidem tenetur porro repudiandae consequatur placeat autem et, distinctio dolorum non iure delectus soluta repellendus eos. Cupiditate, provident. Officia, ullam. Atque saepe facere unde in nesciunt esse assumenda cupiditate id enim!</p>
            </div>
        </main>
    )
}